### ISSUE TITLE
Add nintendo ds support

### ISSUE THREAD

**Issue by wuniversales** [RiiConnect24/DNS-Server#14]
I have added the list "dns_zones-hosts.txt" to my dns, and it works fine on wii, however on my nintendo DS it doesn't connect in online games, it gives me error 61020.

With DNS 164.132.44.106 if the Nintendo DS games work.

I think it is because the IPs are not entered in the "dns_zones-hosts.txt" list.

I have detected the following missing connections.

- mariokartds.available.gs.nintendowifi.net
- gpcm.gs.nintendowifi.net

Obviously there is more. Any help with this?

Thank you

**Comment by 2secslater** [comment]
Correct me if I'm wrong, but it seems `61020` generally means you have a poor connection.

**Comment by 2secslater** [comment]
Also, regarding both domains you mentioned, redirect them to `95.217.77.151` if they aren't being redirected there already.

**Comment by wuniversales** [comment]
Perfect, I just redirected the ip of the two domains above to 95.217.77.151 and now the mario kart works correctly.
Thank you

**Comment by wuniversales** [comment]
I correct, it connects me to the online, but when trying to join online to the world game it gives error "85020" as I have seen, MASTER server is down.
I don't know if it's really well configured, or if it's a server problem.

**Comment by 2secslater** [comment]
Ah, that's apparently common for hotspot users or those with closed ports. Try putting your Nintendo DS into DMZ via your router's settings. Usually this can be found under firewall settings.
![DMZ settings on a BT Home Hub 6 router](https://0x0.st/iQYH.png)

**Comment by wuniversales** [comment]
I am using NextDNS to do the redirects.
https://nextdns.io/
I don't have that option.

**Comment by urmum-69** [comment]
I think that error generally means shitty connection. Move closer to your router if you can.

**Comment by wuniversales** [comment]
I am near the fiber router.

Now it gives me this error "84020", with the dns "164.132.44.106" it gives error "85020", it seems to me that they are the servers, which for whatever reason do not work.

I give it as "Solved", I'll try to connect later to see if it works.

Add the missing dns on the fork:

mariokartds.ms17.gs.nintendowifi.net - 95.217.77.151
mariokartds.master.gs.nintendowifi.net - 95.217.77.151

Thank you

**Comment by Artuto** [comment]
Fixed in #15

**Comment by wuniversales** [comment]
These two are missing
mariokartds.ms17.gs.nintendowifi.net - 95.217.77.151
mariokartds.master.gs.nintendowifi.net - 95.217.77.151
