### ISSUE TITLE
sudomemoDNS updated to use MIT License

### ISSUE THREAD

**Issue by sudofox** [RiiConnect24/DNS-Server#23]
Was doing some thinking about open source and decided to republish sudomemo/sudomemoDNS under the MIT License instead of the vague "all rights reserved". I must confess that I wasn't very experienced with licenses back then. Hopefully this can clear up any worries you've got about your fork.

**Comment by larsenv** [comment]
Would you like us to update the license?

**Comment by sudofox** [comment]
Yes, that'd be great. Glad to see that it's been useful to you.
